id: P008097
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG01645
  title: མཐོང་གྲོལ་ཞྭ་བཤད
  author: ''
  volumes:
    56112cccb4644ba2a143e366b14f492b:
      image_group_id: I00KG02949
      title: ''
      volume_number: 1
      total_pages: 10
ebook_metadata:
  title: མཐོང་གྲོལ་ཞྭ་བཤད
  author: ''
  sku: P008097
  cover: cover.jpg
  layers:
  - pagination
