id: P008097
initial_creation_type: ocr
source_metadata:
  id: bdr:W00KG01645
  title: མཐོང་གྲོལ་ཞྭ་བཤད
  author: ''
  volumes:
    0ba1f142189645fcb49cb445c3132b00:
      image_group_id: I00KG02949
      title: Volume 1 of mthong grol zhwa bshad
      volume_number: 1
      total_pages: 10
      base_file: v001.txt
ebook_metadata:
  title: མཐོང་གྲོལ་ཞྭ་བཤད
  author: ''
  sku: P008097
  cover: cover.jpg
  layers:
  - pagination
