id: P008097
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 13:01:21.785518
source_metadata:
  id: bdr:W00KG01645
  title: མཐོང་གྲོལ་ཞྭ་བཤད
  author: ''
  volumes:
    0ba1f142189645fcb49cb445c3132b00:
      image_group_id: I00KG02949
      title: Volume 1 of mthong grol zhwa bshad
      volume_number: 1
      total_pages: 10
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
